name: simtack
description: "Simtack: A Tactile Human Digital Twin Architecture for Accessible Medical Triage"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  model_viewer_plus: ^1.7.0
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.6
  camera: ^0.10.5
  permission_handler: ^11.0.1
  math_expressions: ^2.4.0  
  share_plus: ^7.2.1         # To share the link or image
  universal_html: ^2.2.4     # REQUIRED: For triggering web downloads
  cross_file: ^0.3.4+2
  pointer_interceptor: ^0.10.1
  intl: ^0.19.0     # REQUIRED: For handling file data in share_plus
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/avatars/